---
- name: Check configuration attribute facts
  ansible.builtin.set_fact:
    _postgresql_datadir_attr: data_directory

- name: Check postgres configuration attributes
  ansible.builtin.assert:
    that:
      - _postgresql_datadir_attr in _postgresql_config

- name: Set configuration facts
  ansible.builtin.set_fact:
    _postgresql_datadir: "{{ _postgresql_config.data_directory }}"
    _postgresql_hba: "{{ _postgresql_config.hba_file }}"
    _postgresql_ident: "{{ _postgresql_config.ident_file }}"

- name: Check datadir configuration
  ansible.builtin.assert:
    that:
      - _postgresql_config[_postgresql_datadir_attr] == _postgresql_datadir
    fail_msg: postgresql_datadir attribute must match requested configuration

- name: Create PostgreSQL data directory
  ansible.builtin.file:
    path: "{{ _postgresql_datadir }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700

- name: Check if PostgreSQL database is initialized
  ansible.builtin.stat:
    path: "{{ _postgresql_datadir }}/PG_VERSION"
  register: pgdatadir_stat

- name: Initialize PostgreSQL database
  ansible.builtin.command: "{{ _postgresql_bindir }}/initdb -D {{ _postgresql_datadir }}"
  when: not pgdatadir_stat.stat.exists
  become: true
  become_user: "{{ postgresql_user }}"

- name: Set PostgreSQL environment variables
  ansible.builtin.template:
    src: postgres.sh.j2
    dest: /etc/profile.d/postgres.sh
    mode: 0644
    owner: root
    group: root
  notify: postgresql_restart

- name: Manage PostgreSQL main config
  ansible.builtin.template:
    src: postgres.conf.j2
    dest: "{{ _postgresql_datadir }}/postgresql.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0644
