---
- name: Install required pips
  ansible.builtin.pip:
    name: psycopg2-binary
    state: "{{ postgresql_pip_state }}"
  when: postgresql_pip_manage

- name: Stat postgres datadir
  ansible.builtin.stat:
    path: "{{ _postgresql_datadir }}"
  register: _datadir_query

- name: Set database initialization flags
  ansible.builtin.set_fact:
    _postgresql_checksum_enable: "{{ not _datadir_query.stat.exists }}"

- name: Release package holds
  ansible.builtin.include_tasks: lock.yml
  vars:
    _lock_state: install

- name: Configure cluster initialization for Debian distributions
  when: ansible_os_family == "Debian"
  block:
    - name: Install postgresql common package
      ansible.builtin.package:
        name: postgresql-common

    - name: Disable database initialization
      ansible.builtin.copy:
        dest: "/etc/postgresql-common/createcluster.conf"
        content: |
          create_main_cluster = off
      when: not (_postgresql_initdb | bool)

- name: Install packages and configure package holds
  block:
    - name: Install postgresql packages
      ansible.builtin.package:
        name: "{{ _postgresql_package_name }}"
        state: "{{ postgresql_package_state }}"

  always:
    - name: Configure package holds
      ansible.builtin.include_tasks: lock.yml
      vars:
        _lock_state: hold
      when: postgresql_package_state != 'absent'
