---
- name: Install required pips
  ansible.builtin.pip:
    name: psycopg2-binary
    state: "{{ postgresql_pip_state }}"
  when: postgresql_pip_manage

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Set package initialization flags
  ansible.builtin.set_fact:
    _postgresql_checksum_enable: "{{ _postgresql_package_server not in ansible_facts.packages }}"

- name: Release package holds
  ansible.builtin.include_tasks: lock.yml
  vars:
    _lock_state: install

- name: Install packages and configure package holds
  block:
    - name: Install postgresql packages
      ansible.builtin.package:
        name: "{{ _packages }}"
        state: "{{ postgresql_package_state }}"
      vars:
        _packages: "{{ ([_postgresql_package_server] | flatten) + ([_postgresql_package_extra] | flatten) }}"

  always:
    - name: Configure package holds
      ansible.builtin.include_tasks: lock.yml
      vars:
        _lock_state: hold
      when: postgresql_package_state != 'absent'
