---
- name: Install required pips
  ansible.builtin.pip:
    name: psycopg2-binary
    state: "{{ postgresql_pip_state }}"
  when: postgresql_pip_manage

- name: Stat PostgreSQL datadir
  ansible.builtin.stat:
    path: "{{ _postgresql_datadir }}"
  register: _datadir_query

- name: Set database initialization flags
  ansible.builtin.set_fact:
    _postgresql_checksum_enable: "{{ not _datadir_query.stat.exists }}"

- name: Release package holds
  ansible.builtin.include_tasks: lock.yml
  vars:
    _lock_state: install

- name: Configure cluster initialization for Debian distributions
  when: ansible_os_family == "Debian"
  block:
    - name: Install PostgreSQL common package
      ansible.builtin.package:
        name: postgresql-common

    - name: Disable database initialization
      ansible.builtin.copy:
        dest: "/etc/postgresql-common/createcluster.conf"
        content: |
          create_main_cluster = off
        owner: root
        group: root
        mode: 0644
      when: not (_postgresql_initdb | bool)

- name: Install packages and configure package holds
  block:
    - name: Install PostgreSQL server packages
      ansible.builtin.package:
        name: "{{ _server + _extra }}"
        state: "{{ postgresql_package_state }}"
      vars:
        _server: "{{ [_postgresql_package_name] | flatten }}"
        _extra: "{{ [_postgresql_package_extra] | flatten }}"

  always:
    - name: Configure package holds
      ansible.builtin.include_tasks: lock.yml
      vars:
        _lock_state: hold
      when: postgresql_package_state != 'absent'

- name: Manage PostgreSQL service configuration
  when: ansible_os_family == 'RedHat'
  block:
    - name: Set system facts
      ansible.builtin.set_fact:
        _postgresql_dropin: "/etc/systemd/system/{{ _postgresql_service_name }}.service.d/pgdata.conf"

    - name: Create systemd drop-in directory
      ansible.builtin.file:
        path: "{{ _postgresql_dropin | dirname }}"
        owner: root
        group: root
        state: directory
        mode: 0755

    - name: Create systemd drop-in configuration
      ansible.builtin.copy:
        dest: "{{ _postgresql_dropin }}"
        content: |
          [Service]
          Environment=PGDATA={{ _postgresql_datadir }}
          ExecStart=
          ExecStart=/usr/pgsql-16/bin/postgres -D ${PGDATA} -c config_file={{ _postgresql_conf_main }}
        owner: root
        group: root
        mode: 0644
      notify: daemon_reload
