---
- name: Set installation facts
  ansible.builtin.include_tasks: vars.yml

- name: Install PostgreSQL services
  ansible.builtin.include_tasks: install.yml

- name: Configure PostgreSQL services
  when: postgresql_package_state != 'absent'
  block:
    - name: Manage PostgreSQL configuration
      ansible.builtin.include_tasks: configure.yml

    - name: Manage PostgreSQL services
      ansible.builtin.include_tasks: service.yml

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Manage PostgreSQL roles
      ansible.builtin.include_tasks: roles.yml
      when: postgresql_service_state == 'started'

    - name: Manage PostgreSQL databases
      ansible.builtin.include_tasks: databases.yml
      when: postgresql_service_state == 'started'

    - name: Manage PostgreSQL extensions
      ansible.builtin.include_tasks: extensions.yml
      when: postgresql_service_state == 'started'
