---
- name: Manage install tasks
  ansible.builtin.include_tasks: install.yml

- name: Manage role tasks
  ansible.builtin.include_tasks: roles.yml

- name: Manage database tasks
  ansible.builtin.include_tasks: databases/manage.yml

- name: Manage database privilege tasks
  ansible.builtin.include_tasks: databases/privileges.yml
