---
- name: Install postgresql packages
  ansible.builtin.package:
    name: "{{ postgresql_package_name }}"
    state: "{{ postgresql_package_state }}"

- name: Manage postgresql services
  include_tasks: service.yml
