---
- name: Set installation facts
  ansible.builtin.include_tasks: vars.yml

- name: Install PostgreSQL services
  ansible.builtin.include_tasks: service.yml

- name: Manage PostgreSQL services
  ansible.builtin.include_tasks: service.yml
