---
- name: Manage PostgreSQL pgaudit include config
  ansible.builtin.copy:
    dest: "{{ _postgresql_conf_pgaudit }}"
    content: "{{ postgresql_conf_pgaudit }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0644
  when: postgresql_conf_pgaudit is defined
  notify: postgresql_reload

- name: Destroy PostgreSQL pgaudit include config
  ansible.builtin.file:
    path: "{{ _postgresql_conf_pgaudit }}"
    state: absent
  when: postgresql_conf_pgaudit is not defined
  notify: postgresql_reload

- name: Query pgaudit extension
  community.postgresql.postgresql_query:
    query: "SELECT * FROM pg_extension WHERE extname = 'pgaudit'"
    db: postgres
  become: true
  become_user: "{{ postgresql_user }}"
  register: _extension_query
  changed_when: false

- name: Query pgaudit extension
  community.postgresql.postgresql_query:
    query: "CREATE EXTENSION pgaudit"
    db: postgres
  become: true
  become_user: "{{ postgresql_user }}"
  when: _extension_query.rowcount == 0

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
