---
- name: Manage PostgreSQL pgcron include config
  ansible.builtin.copy:
    dest: "{{ _postgresql_conf_pgcron }}"
    content: "{{ postgresql_conf_pgcron }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0644
  when: postgresql_conf_pgcron is defined
  notify: postgresql_reload

- name: Destroy PostgreSQL pgcron include config
  ansible.builtin.file:
    path: "{{ _postgresql_conf_pgcron }}"
    state: absent
  when: postgresql_conf_pgcron is not defined
  notify: postgresql_reload

- name: Query pgcron extension
  community.postgresql.postgresql_query:
    query: "SELECT * FROM pg_extension WHERE extname = 'pg_cron'"
    db: postgres
  become: true
  become_user: "{{ postgresql_user }}"
  register: _extension_query
  changed_when: false

- name: Deploy pgcron extension
  community.postgresql.postgresql_query:
    query: "CREATE EXTENSION pg_cron"
    db: postgres
  become: true
  become_user: "{{ postgresql_user }}"
  when: _extension_query.rowcount == 0
