---
- name: Manage PostgreSQL pgstat_statements include config
  ansible.builtin.copy:
    dest: "{{ _postgresql_conf_pgstat_statements }}"
    content: "{{ postgresql_conf_pgstat_statements }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0644
  when: postgresql_conf_pgstat_statements is defined
  notify: postgresql_reload

- name: Destroy PostgreSQL pgstat_statements include config
  ansible.builtin.file:
    path: "{{ _postgresql_conf_pgstat_statements }}"
    state: absent
  when: postgresql_conf_pgstat_statements is not defined
  notify: postgresql_reload

- name: Query pgstat_statements extension
  community.postgresql.postgresql_query:
    query: "SELECT * FROM pg_extension WHERE extname = 'pgstat_statements'"
    db: postgres
  become: true
  become_user: "{{ postgresql_user }}"
  register: _extension_query
  changed_when: false

- name: Query pgstat_statements extension
  community.postgresql.postgresql_query:
    query: "CREATE EXTENSION pgstat_statements"
    db: postgres
  become: true
  become_user: "{{ postgresql_user }}"
  when: _extension_query.rowcount == 0

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
