---
- name: Manage postgresql service
  ansible.builtin.service:
    name: "{{ postgresql_service_name }}"
    state: "{{ postgresql_service_state }}"

    enabled: "{{ postgresql_service_enabled }}"
  when: postgresql_package_state != 'absent'
