---
- name: Set global facts
  ansible.builtin.set_fact:
    _postgresql_package_name: "{{ postgresql_package_name | default(_default_package) }}"
    _postgresql_service_name: "{{ postgresql_service_name | default(_default_service) }}"
    _postgresql_bindir: "{{ __postgresql_bindir | nephelaiio.plugins.sorted_get(_conf_search) }}"
    _postgresql_datadir: "{{ postgresql_datadir }}"
    _postgresql_waldir: "{{ postgresql_waldir }}"
    _postgresql_pgoptions: "{{ (_auth_method == _auth_scram_sha256) | ternary(_auth_scram_option, '') }}"
    _postgresql_conf_include: "{{ _conf_include }}"
    _postgresql_conf_main: "{{ _conf_main }}"
    _postgresql_conf_hba: "{{ postgresql_datadir }}/pg_hba.conf"
    _postgresql_conf_ident: "{{ postgresql_datadir }}/pg_ident.conf"
    _postgresql_conf_ansible: "{{ _conf_include }}/{{ __postgresql_conf_ansible }}"
    _postgresql_conf_pgaudit: "{{ _conf_include }}/{{ __postgresql_conf_pgaudit }}"
    _postgresql_conf_pgcron: "{{ _conf_include }}/{{ __postgresql_conf_pgcron }}"
    _postgresql_conf_pgstat_statements: "{{ _conf_include }}/{{ __postgresql_conf_pgstat_statements }}"
    _postgresql_conf_standby: "{{ _conf_include }}/{{ __postgresql_conf_standby }}"
    _postgresql_conf_local: "{{ _conf_include }}/{{ __postgresql_conf_local }}"
    _postgresql_conf_exclude: "{{ __postgresql_conf_exclude }}"
  vars:
    _default_package: "{{ __postgresql_package_name | nephelaiio.plugins.sorted_get(_conf_search) }}"
    _default_service: "{{ __postgresql_service_name | nephelaiio.plugins.sorted_get(_conf_search) }}"
    _conf_search: "{{ __postgresql_os_search }}"
    _conf_include: "{{ postgresql_datadir }}/conf.d"
    _conf_main: "{{ __postgresql_conf_main | nephelaiio.plugins.sorted_get(_conf_search) }}"
    _auth_scram_sha256: "scram-sha-256"
    _auth_scram_option: '-c password_encryption={{ _auth_scram_sha256 }}'
    _auth_method: "{{ postgresql_auth_method }}"
