---
- name: Converge
  hosts: all
  become: true
  roles:
    - nephelaiio.postgresql
  pre_tasks:
    - name: Create virtualenv
      ansible.builtin.tempfile:
        state: directory
        prefix: .virtualenv
        path: "~"
      register: _virtualenv_tmpdir
      changed_when: false

    - name: Initialize virtualenv
      ansible.builtin.pip:
        name:
          - psycopg2-binary
        virtualenv: "{{ _virtualenv_tmpdir.path }}/venv"
      changed_when: false

  post_tasks:
    - name: Destroy virtualenv
      ansible.builtin.file:
        path: "{{ _virtualenv_tmpdir.path }}"
        state: absent
      changed_when: false
