---
- name: Set installation facts
  ansible.builtin.include_tasks: vars.yml

- name: Restart PostgreSQL
  ansible.builtin.service:
    name: "{{ _postgresql_service }}"
    state: "restarted"
  listen: postgresql_restart
