---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-"/lib/systemd/systemd"}
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    tmpfs:
      - /tmp
      - /opt
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  inventory:
    hosts:
      all:
        vars:
          postgresql_user: postgres
          postgresql_roles:
            - name: admin
              password: admin
              groups:
                - name: admins
            - name: user
              password: user
              groups:
                - name: read_only
            - name: admins
              role_attr_flags: "NOLOGIN"
            - name: read_only
              role_attr_flags: "NOLOGIN"
          postgresql_databases:
            - name: database
              encoding: "UNICODE"
              roles:
                - name: admins
                  privs: ALL
                  type: database
                  objs: database
                - name: read_only
                  privs: ALL
                  type: database
                  objs: database
verifier:
  name: ansible
