- name: Verify PostgreSQL deployment
  hosts: all
  become: true
  tasks:
    - name: Import role defaults
      ansible.builtin.include_role:
        name: nephelaiio.postgresql
        tasks_from: vars.yml

    - name: Query Debian server package versions
      ansible.builtin.shell:
        cmd: "apt-cache madison {{ item }} | awk -F'|' '{ print $2 }'"
      loop: "{{ _postgresql_package_server }}"
      register: _debian_package_server
      when: ansible_os_family == "Debian"
      changed_when: false

    - name: Query Debian client package versions
      ansible.builtin.shell:
        cmd: "apt-cache madison {{ item }} | awk -F'|' '{ print $2 }'"
      loop: "{{ _postgresql_package_client }}"
      register: _debian_package_client
      when: ansible_os_family == "Debian"
      changed_when: false

    - name: Query RedHat server package versions
      ansible.builtin.shell:
        cmd: "yum list {{ item }} --showduplicates | grep '^{{ item }}' | awk '{ print $1,$2 }' | sort -r"
      loop: "{{ _postgresql_package_server }}"
      register: _redhat_package_server
      when: ansible_os_family == "RedHat"
      changed_when: false

    - name: Query RedHat client package versions
      ansible.builtin.shell:
        cmd: "yum list {{ item }} --showduplicates | grep '^{{ item }}' | awk '{ print $1,$2 }' | sort -r"
      loop: "{{ _postgresql_package_client }}"
      register: _redhat_package_client
      when: ansible_os_family == "RedHat"
      changed_when: false

    - name: Set package version facts
      ansible.builtin.set_fact:
        _postgresql_package_server_query: "{{ _redhat_server + _debian_server }}"
        _postgresql_package_client_query: "{{ _redhat_client + _debian_client }}"
      vars:
        _redhat_server: "{{ [] if _redhat_package_server.skipped else _redhat_server_package.results }}"
        _debian_server: "{{ [] if _debian_package_server.skipped else _debian_server_package.results }}"
        _redhat_client: "{{ [] if _redhat_package_client.skipped else _redhat_client_package.results }}"
        _debian_client: "{{ [] if _debian_package_client.skipped else _debian_client_package.results }}"

    - name: Verify target server package versions
      ansible.builtin.fail:
        msg: "{{ _package }} has no installation candidate: {{ item }}"
      vars:
        _stdout: "{{ item.stdout_lines }}"
        _package: "{{ item.item }}"
      loop_control:
        label: "{{ item.item }}"
      loop: "{{ _postgresql_package_server_query }}"
      when: _stdout | length == 0

    - name: Verify target client package versions
      ansible.builtin.fail:
        msg: "{{ _package }} has no installation candidate: {{ item }}"
      vars:
        _stdout: "{{ item.stdout_lines }}"
        _package: "{{ item.item }}"
      loop_control:
        label: "{{ item.item }}"
      loop: "{{ _postgresql_package_client_query }}"
      when: _stdout | length == 0

    - name: Initialize package versions
      ansible.builtin.set_fact:
        postgresql_package_server_list: []

    - name: Set target Debian server package versions
      ansible.builtin.set_fact:
        postgresql_package_server_list: "{{ postgresql_package_server_list + [_package] }}"
      vars:
        _stdout: "{{ item.stdout_lines }}"
        _multiple: "{{ _stdout | length > 1 }}"
        _version: "{{ _stdout[0] if not _multiple else _stdout[1] }}"
        _package: "{{ item.item }}={{ _version | trim }}"
      loop_control:
        label: "{{ item.item }}"
      loop: "{{ _postgresql_package_server_query }}"
      when: ansible_os_family == "Debian"

    - name: Set target Debian client package versions
      ansible.builtin.set_fact:
        postgresql_package_client_list: "{{ postgresql_package_client_list + [_package] }}"
      vars:
        _stdout: "{{ item.stdout_lines }}"
        _multiple: "{{ _stdout | length > 1 }}"
        _version: "{{ _stdout[0] if not _multiple else _stdout[1] }}"
        _package: "{{ item.item }}={{ _version | trim }}"
      loop_control:
        label: "{{ item.item }}"
      loop: "{{ _postgresql_package_client_query }}"
      when: ansible_os_family == "Debian"

    - name: Set target RedHat server package versions
      ansible.builtin.set_fact:
        postgresql_package_server_list: "{{ postgresql_package_server_list + [_package] }}"
      vars:
        _stdout: "{{ item.stdout_lines }}"
        _multiple: "{{ _stdout | length > 1 }}"
        _target: "{{ (_stdout[0] if not _multiple else _stdout[1]).split(' ') }}"
        _arch: "{{ _target[0].split('.')[1] }}"
        _name: "{{ _target[0].split('.')[0] }}"
        _version: "{{ _target[1] }}"
        _package: "{{ _name }}-{{ _version }}.{{ _arch }}"
      loop_control:
        label: "{{ item.item }}"
      loop: "{{ _postgresql_package_server_query }}"
      when: ansible_os_family == "RedHat"

    - name: Set target RedHat client package versions
      ansible.builtin.set_fact:
        postgresql_package_client_list: "{{ postgresql_package_client_list + [_package] }}"
      vars:
        _stdout: "{{ item.stdout_lines }}"
        _multiple: "{{ _stdout | length > 1 }}"
        _target: "{{ (_stdout[0] if not _multiple else _stdout[1]).split(' ') }}"
        _arch: "{{ _target[0].split('.')[1] }}"
        _name: "{{ _target[0].split('.')[0] }}"
        _version: "{{ _target[1] }}"
        _package: "{{ _name }}-{{ _version }}.{{ _arch }}"
      loop_control:
        label: "{{ item.item }}"
      loop: "{{ _postgresql_package_client_query }}"
      when: ansible_os_family == "RedHat"

    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: Verify Debian server package versions
      ansible.builtin.assert:
        that:
          - _package in packages
          - _version == _installed
        fail_msg: "Expected {{ _package }}={{ _version }}, found {{ _package }}={{ _installed }}"
        success_msg: "Found {{ _package }}={{ _version }}"
      vars:
        _package: "{{ item.split('=') | first }}"
        _version: "{{ item.split('=') | last }}"
        _installed: "{{ (packages[_package] | default([{'version': 'None'}]))[0].version }}"
      loop: "{{ postgresql_package_server_list }}"
      when: ansible_os_family == "Debian"

    - name: Verify Debian client package versions
      ansible.builtin.assert:
        that:
          - _package in packages
          - _version == _installed
        fail_msg: "Expected {{ _package }}={{ _version }}, found {{ _package }}={{ _installed }}"
        success_msg: "Found {{ _package }}={{ _version }}"
      vars:
        _package: "{{ item.split('=') | first }}"
        _version: "{{ item.split('=') | last }}"
        _installed: "{{ (packages[_package] | default([{'version': 'None'}]))[0].version }}"
      loop: "{{ postgresql_package_client_list }}"
      when: ansible_os_family == "Debian"

    - name: Verify RedHat server package versions
      ansible.builtin.assert:
        that:
          - _package in packages
          - _version == _installed
        fail_msg: "Expected {{ _package }}={{ _version }}, found {{ _package }}={{ _installed }}"
        success_msg: "Found {{ _package }}={{ _version }}"
      vars:
        _prefix: "^{{ _package }}-"
        _suffix: "-.*$"
        _package: "{{ item.0 }}"
        _version: "{{ item.1 | regex_replace(_prefix, '') | regex_replace(_suffix, '') }}"
        _installed: "{{ (packages[_package] | default([{'version': 'None'}]))[0].version }}"
      loop: "{{ _postgresql_package_server | zip(postgresql_package_server_list) }}"
      when: ansible_os_family == "RedHat"

    - name: Verify RedHat client package versions
      ansible.builtin.assert:
        that:
          - _package in packages
          - _version == _installed
        fail_msg: "Expected {{ _package }}={{ _version }}, found {{ _package }}={{ _installed }}"
        success_msg: "Found {{ _package }}={{ _version }}"
      vars:
        _prefix: "^{{ _package }}-"
        _suffix: "-.*$"
        _package: "{{ item.0 }}"
        _version: "{{ item.1 | regex_replace(_prefix, '') | regex_replace(_suffix, '') }}"
        _installed: "{{ (packages[_package] | default([{'version': 'None'}]))[0].version }}"
      loop: "{{ _postgresql_package_client | zip(postgresql_package_client_list) }}"
      when: ansible_os_family == "RedHat"

    - name: Verify apt server package locks
      ansible.builtin.command:
        cmd: "apt-mark showhold | grep {{ item }}"
      loop: "{{ _postgresql_package_server }}"
      when: ansible_os_family == "Debian"
      changed_when: false

    - name: Verify apt client package locks
      ansible.builtin.command:
        cmd: "apt-mark showhold | grep {{ item }}"
      loop: "{{ _postgresql_package_client }}"
      when: ansible_os_family == "Debian"
      changed_when: false

    - name: Verify yum server package locks
      ansible.builtin.command:
        cmd: "grep {{ item }} /etc/yum/pluginconf.d/versionlock.list"
      loop: "{{ _postgresql_package_server }}"
      when: ansible_os_family == "RedHat"
      changed_when: false

    - name: Verify yum client package locks
      ansible.builtin.command:
        cmd: "grep {{ item }} /etc/yum/pluginconf.d/versionlock.list"
      loop: "{{ _postgresql_package_client }}"
      when: ansible_os_family == "RedHat"
      changed_when: false
